// Copies the SliceAuction ABI from the Foundry build output into lib/abi.ts.
// Run `forge build` in ../contracts first, then `npm run sync-abi`.
import { readFileSync, writeFileSync } from "node:fs";

const artifact = JSON.parse(
  readFileSync(new URL("../../contracts/out/SliceAuction.sol/SliceAuction.json", import.meta.url)),
);
const out = `// Generated by scripts/sync-abi.mjs. Do not edit by hand.
export const sliceAuctionAbi = ${JSON.stringify(artifact.abi, null, 2)} as const;
`;
writeFileSync(new URL("../lib/abi.ts", import.meta.url), out);
console.log(`Wrote lib/abi.ts (${artifact.abi.length} entries)`);
